# Generated by Django 2.2.6 on 2019-10-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Gönderi', 'verbose_name_plural': 'Gönderiler'},
        ),
    ]
