# Generated by Django 2.2.6 on 2019-10-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(help_text='Kapak Fotoğrafı Seçiniz', null=True, upload_to='', verbose_name='Resim'),
        ),
    ]
