# Generated by Django 2.2.6 on 2019-10-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191012_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default/default.png', help_text='Kapak Fotoğrafı Seçiniz', null=True, upload_to='', verbose_name='Resim'),
        ),
    ]
