# Generated by Django 2.2.6 on 2019-10-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191012_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='yayin_taslak',
            field=models.CharField(blank=True, choices=[(None, 'Lütfen Bir Değer Seçiniz'), ('yayin', 'YAYIN'), ('taslak', 'TASLAK')], max_length=7),
        ),
    ]
