# Generated by Django 3.0.5 on 2020-04-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200429_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/defaults/logo.png', upload_to='media/post/'),
        ),
    ]
