# Generated by Django 3.0.5 on 2020-04-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200429_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='defaults/logo.png', upload_to='post/'),
        ),
    ]
