# Generated by Django 2.2.6 on 2020-01-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200122_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='manager',
        ),
        migrations.AddField(
            model_name='customuser',
            name='mudur',
            field=models.ManyToManyField(related_name='mudur', to='users.Manager'),
        ),
    ]
