# Generated by Django 2.2.7 on 2019-11-23 12:15

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191123_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', djgeojson.fields.PointField()),
            ],
        ),
    ]
