# Generated by Django 2.2.5 on 2019-09-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cratead',
            new_name='created',
        ),
    ]
