# Generated by Django 2.2.6 on 2019-11-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_profile_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profiller'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='previous_work',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
