# Generated by Django 2.2.6 on 2019-12-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0002_subcategory_unnecessary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='unnecessary',
        ),
    ]
