# Generated by Django 2.2.6 on 2019-11-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191127_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='facebook_address',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='twitter_address',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='youtube_address',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
