# Generated by Django 2.2.6 on 2019-11-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_main_set_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='link',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='phone',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
