# Generated by Django 2.2.6 on 2019-12-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_main_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='pic_name',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='pic_url',
            field=models.TextField(default='-'),
        ),
    ]
