# Generated by Django 2.2.6 on 2019-12-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
