# Generated by Django 2.2.6 on 2019-12-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_contactform_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='is_it_read',
            field=models.BooleanField(default=False),
        ),
    ]
