# Generated by Django 2.2.6 on 2019-11-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_free',
            field=models.BooleanField(null=True),
        ),
    ]
