# Generated by Django 2.2.6 on 2019-12-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
