# Generated by Django 2.2.6 on 2019-12-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0002_auto_20191229_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trending',
            old_name='name',
            new_name='txt',
        ),
    ]
