# Generated by Django 2.2.6 on 2020-01-05 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_txt', models.TextField()),
                ('body_txt', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pic_name', models.TextField()),
                ('pic_url', models.TextField(default='-')),
                ('category_name', models.CharField(default='-', max_length=255)),
                ('category_id', models.IntegerField(default=0)),
                ('ocategory_id', models.IntegerField(default=0)),
                ('show', models.IntegerField(default=0)),
                ('tag', models.TextField(default='')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
