# Generated by Django 2.2.6 on 2020-01-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='writer',
            field=models.CharField(max_length=50),
        ),
    ]
