# Generated by Django 2.2.6 on 2019-12-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20191213_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='category_name',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='show',
            field=models.IntegerField(default=0),
        ),
    ]
