# Generated by Django 2.2.6 on 2019-12-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20191215_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='pic',
            new_name='pic_name',
        ),
        migrations.AddField(
            model_name='news',
            name='pic_url',
            field=models.TextField(default='-'),
        ),
    ]
